[
  workspace: [
    root: "../..",
    project_globs: ["core/*", "runtime/*"]
  ],
  artifacts: [
    fixture_bundle: [
      roots: ["runtime/local"],
      package: [
        name: "fixture_bundle",
        otp_app: :fixture_bundle,
        version: "0.1.0",
        description: "Fixture bundle generated by weld",
        licenses: ["MIT"],
        links: %{"Source" => "https://example.test/fixture_bundle"}
      ],
      output: [
        docs: [
          "README.md",
          "CHANGELOG.md",
          "guides/architecture.md",
          "guides/getting_started.md"
        ]
      ],
      verify: [
        artifact_tests: ["packaging/weld/fixture_bundle/test"],
        smoke: [
          enabled: true,
          entry_file: "packaging/weld/fixture_bundle/smoke.ex"
        ]
      ]
    ]
  ]
]
