[
  workspace: [
    root: "../..",
    project_globs: ["core/*", "runtime/*"]
  ],
  dependencies: [
    git_dep: [
      opts: [git: "https://example.test/git_dep.git", branch: "main"]
    ]
  ],
  artifacts: [
    monolith_bundle: [
      mode: :monolith,
      roots: ["runtime/api"],
      package: [
        name: "monolith_bundle",
        otp_app: :monolith_bundle,
        version: "0.1.0",
        description: "Fixture bundle generated by weld monolith mode",
        licenses: ["MIT"],
        links: %{"Source" => "https://example.test/monolith_bundle"}
      ],
      output: [
        docs: ["README.md"],
        assets: ["LICENSE"]
      ]
    ]
  ]
]
